# Generated by Django 2.1.11 on 2022-03-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
