# Generated by Django 2.1.11 on 2022-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_puntosacu'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntosacu',
            name='cedula',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
