# Generated by Django 2.1.11 on 2022-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_puntosacu_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Documento'),
        ),
    ]
