# Generated by Django 2.1.11 on 2022-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20220407_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntosacu',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
