# Generated by Django 2.1.11 on 2022-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopiaCie10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'copia_cie10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsdsdsrdenMedica',
            fields=[
                ('ordenmedicaid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('medicoid', models.IntegerField(blank=True, null=True)),
                ('admisionid', models.IntegerField(blank=True, null=True)),
                ('servicioid', models.IntegerField(blank=True, null=True)),
                ('productoid', models.IntegerField(blank=True, null=True)),
                ('estudioid', models.IntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=1, null=True)),
                ('realizada', models.IntegerField(blank=True, null=True)),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True)),
                ('usuarioid', models.IntegerField(blank=True, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidaid', models.IntegerField(blank=True, null=True)),
                ('requisicionid', models.IntegerField(blank=True, null=True)),
                ('hora', models.DateTimeField(blank=True, null=True)),
                ('frecuenciaid', models.IntegerField(blank=True, null=True)),
                ('dosis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('viaid', models.IntegerField(blank=True, null=True)),
                ('medidaid_dosis', models.IntegerField(blank=True, null=True)),
                ('cantidad_requisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('despachada', models.IntegerField(blank=True, null=True)),
                ('fecha_despachada', models.DateTimeField(blank=True, null=True)),
                ('hora_administracion', models.DateTimeField(blank=True, null=True)),
                ('administrada', models.IntegerField(blank=True, null=True)),
                ('emergenciaid', models.IntegerField(blank=True, null=True)),
                ('uci', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('hora_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orden_medica',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='ordenmedica',
            table='ordenmedica',
        ),
    ]
