# Generated by Django 2.1.11 on 2022-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0004_orden_medica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.BigIntegerField(blank=True, null=True)),
                ('Puntos', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
